name: resmart
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: "0.1.0"

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  flutter_dotenv: ^5.2.1
  http: ^1.2.2
  location: ^7.0.1
  flutter_displaymode: ^0.6.0
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.2.0
  weather_icons: ^3.0.0
  wakelock_plus: ^1.2.10
  google_fonts: ^6.1.0
  provider: ^6.0.5
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.1.14
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.10.1 
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2 
  firebase_analytics: ^11.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
