// countries.dart

class Country {
  final String name;
  final String code;
  final String dialCode;

  const Country({
    required this.name,
    required this.code, 
    required this.dialCode,
  });
}

final List<Country> countries = [
  Country(name: 'Afghanistan', code: 'AF', dialCode: '+93'),
  Country(name: 'Albania', code: 'AL', dialCode: '+355'),
  Country(name: 'Algeria', code: 'DZ', dialCode: '+213'),
  Country(name: 'Andorra', code: 'AD', dialCode: '+376'),
  Country(name: 'Angola', code: 'AO', dialCode: '+244'),
  Country(name: 'Argentina', code: 'AR', dialCode: '+54'),
  Country(name: 'Australia', code: 'AU', dialCode: '+61'),
  Country(name: 'Austria', code: 'AT', dialCode: '+43'),
  Country(name: 'Bahamas', code: 'BS', dialCode: '+1-242'),
  Country(name: 'Bahrain', code: 'BH', dialCode: '+973'),
  Country(name: 'Bangladesh', code: 'BD', dialCode: '+880'),
  Country(name: 'Belarus', code: 'BY', dialCode: '+375'),
  Country(name: 'Belgium', code: 'BE', dialCode: '+32'),
  Country(name: 'Bolivia', code: 'BO', dialCode: '+591'),
  Country(name: 'Brazil', code: 'BR', dialCode: '+55'),
  Country(name: 'Bulgaria', code: 'BG', dialCode: '+359'),
  Country(name: 'Cambodia', code: 'KH', dialCode: '+855'),
  Country(name: 'Cameroon', code: 'CM', dialCode: '+237'),
  Country(name: 'Canada', code: 'CA', dialCode: '+1'),
  Country(name: 'Chile', code: 'CL', dialCode: '+56'),
  Country(name: 'China', code: 'CN', dialCode: '+86'),
  Country(name: 'Colombia', code: 'CO', dialCode: '+57'),
  Country(name: 'Costa Rica', code: 'CR', dialCode: '+506'),
  Country(name: 'Croatia', code: 'HR', dialCode: '+385'),
  Country(name: 'Cuba', code: 'CU', dialCode: '+53'),
  Country(name: 'Czech Republic', code: 'CZ', dialCode: '+420'),
  Country(name: 'Denmark', code: 'DK', dialCode: '+45'),
  Country(name: 'Dominican Republic', code: 'DO', dialCode: '+1-809'),
  Country(name: 'Ecuador', code: 'EC', dialCode: '+593'),
  Country(name: 'Egypt', code: 'EG', dialCode: '+20'),
  Country(name: 'El Salvador', code: 'SV', dialCode: '+503'),
  Country(name: 'Estonia', code: 'EE', dialCode: '+372'),
  Country(name: 'Ethiopia', code: 'ET', dialCode: '+251'),
  Country(name: 'Finland', code: 'FI', dialCode: '+358'),
  Country(name: 'France', code: 'FR', dialCode: '+33'),
  Country(name: 'Germany', code: 'DE', dialCode: '+49'),
  Country(name: 'Ghana', code: 'GH', dialCode: '+233'),
  Country(name: 'Greece', code: 'GR', dialCode: '+30'),
  Country(name: 'Guatemala', code: 'GT', dialCode: '+502'),
  Country(name: 'Honduras', code: 'HN', dialCode: '+504'),
  Country(name: 'Hong Kong', code: 'HK', dialCode: '+852'),
  Country(name: 'Hungary', code: 'HU', dialCode: '+36'),
  Country(name: 'Iceland', code: 'IS', dialCode: '+354'),
  Country(name: 'India', code: 'IN', dialCode: '+91'),
  Country(name: 'Indonesia', code: 'ID', dialCode: '+62'),
  Country(name: 'Iran', code: 'IR', dialCode: '+98'),
  Country(name: 'Iraq', code: 'IQ', dialCode: '+964'),
  Country(name: 'Ireland', code: 'IE', dialCode: '+353'),
  Country(name: 'Israel', code: 'IL', dialCode: '+972'),
  Country(name: 'Italy', code: 'IT', dialCode: '+39'),
  Country(name: 'Jamaica', code: 'JM', dialCode: '+1-876'),
  Country(name: 'Japan', code: 'JP', dialCode: '+81'),
  Country(name: 'Kenya', code: 'KE', dialCode: '+254'),
  Country(name: 'Mexico', code: 'MX', dialCode: '+52'),
  Country(name: 'Netherlands', code: 'NL', dialCode: '+31'),
  Country(name: 'New Zealand', code: 'NZ', dialCode: '+64'),
  Country(name: 'Nigeria', code: 'NG', dialCode: '+234'),
  Country(name: 'Norway', code: 'NO', dialCode: '+47'),
  Country(name: 'Pakistan', code: 'PK', dialCode: '+92'),
  Country(name: 'Philippines', code: 'PH', dialCode: '+63'),
  Country(name: 'Poland', code: 'PL', dialCode: '+48'),
  Country(name: 'Portugal', code: 'PT', dialCode: '+351'),
  Country(name: 'Qatar', code: 'QA', dialCode: '+974'),
  Country(name: 'Russia', code: 'RU', dialCode: '+7'),
  Country(name: 'Saudi Arabia', code: 'SA', dialCode: '+966'),
  Country(name: 'Singapore', code: 'SG', dialCode: '+65'),
  Country(name: 'South Africa', code: 'ZA', dialCode: '+27'),
  Country(name: 'South Korea', code: 'KR', dialCode: '+82'),
  Country(name: 'Spain', code: 'ES', dialCode: '+34'),
  Country(name: 'Sri Lanka', code: 'LK', dialCode: '+94'),
  Country(name: 'Sweden', code: 'SE', dialCode: '+46'),
  Country(name: 'Switzerland', code: 'CH', dialCode: '+41'),
  Country(name: 'Thailand', code: 'TH', dialCode: '+66'),
  Country(name: 'Turkey', code: 'TR', dialCode: '+90'),
  Country(name: 'United Arab Emirates', code: 'AE', dialCode: '+971'),
  Country(name: 'United Kingdom', code: 'GB', dialCode: '+44'),
  Country(name: 'United States', code: 'US', dialCode: '+1'),
  Country(name: 'Vietnam', code: 'VN', dialCode: '+84'),
  Country(name: 'Zimbabwe', code: 'ZW', dialCode: '+263'),
];
