// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ErhrPbIj50Ed5xV9m_M--yZ49TkEcJ4',
    appId: '1:348325010680:web:b80d77bfe85eb6e3b36f0d',
    messagingSenderId: '348325010680',
    projectId: 'ivin-techz-account-management',
    authDomain: 'ivin-techz-account-management.firebaseapp.com',
    storageBucket: 'ivin-techz-account-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEg3fTDK6Ne-ULKsBuK3tuEdzvt5YAhos',
    appId: '1:348325010680:android:8953954a5f4dd87cb36f0d',
    messagingSenderId: '348325010680',
    projectId: 'ivin-techz-account-management',
    storageBucket: 'ivin-techz-account-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSZgDiyPPMWEYsYn_iaUjkFADxm1Tbll8',
    appId: '1:348325010680:ios:a8349062f3e84e37b36f0d',
    messagingSenderId: '348325010680',
    projectId: 'ivin-techz-account-management',
    storageBucket: 'ivin-techz-account-management.firebasestorage.app',
    iosBundleId: 'com.example.resmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSZgDiyPPMWEYsYn_iaUjkFADxm1Tbll8',
    appId: '1:348325010680:ios:a8349062f3e84e37b36f0d',
    messagingSenderId: '348325010680',
    projectId: 'ivin-techz-account-management',
    storageBucket: 'ivin-techz-account-management.firebasestorage.app',
    iosBundleId: 'com.example.resmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ErhrPbIj50Ed5xV9m_M--yZ49TkEcJ4',
    appId: '1:348325010680:web:73412a25217f218ab36f0d',
    messagingSenderId: '348325010680',
    projectId: 'ivin-techz-account-management',
    authDomain: 'ivin-techz-account-management.firebaseapp.com',
    storageBucket: 'ivin-techz-account-management.firebasestorage.app',
  );
}
